### ISSUE TITLE
have you published a paper on this work?

### ISSUE THREAD

**Issue by bjtuhpl** [manwaarkhd/CEPHMark-Net#1]
Hello, have you published a paper on this work? Or have you consulted the ideas of which papers? I would like to quote this work.Thank you! @manwaarkhd @Vision-At-SEECS

**Comment by manwaarkhd** [comment]
@bjtuhpl, the paper has been published in **_Expert Systems with Applications_** and can be found at [link](https://www.sciencedirect.com/science/article/abs/pii/S095741742401707X).
